spring:
  application:
    name: ChatApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app_db
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  security:
    user:
      password: 123
      username: abror

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

jwt:
  secret:
    key: coder24_me
  token:
    validity: 86400000
